repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        description: Export production requirements
        entry: poetry export -o requirements.txt
        language: python
        pass_filenames: false
      - id: dev-requirements
        name: dev-requirements
        description: Export production and development requirements
        entry: poetry export --with dev -o requirements-dev.txt
        language: python
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
